services:
  viteapp:
    container_name: viteapp
    image: viteapp:1.0.0
    build:
      context: ./
      dockerfile: ./docker/react/Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - go
  go: 
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./
      dockerfile: ./docker/golang/Dockerfile
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable'
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}